# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(choices=[('MPESA', 'M-pesa'), ('PESALINK', 'Pesalink'), ('PAYPAL', 'Paypal'), ('CHEQUE DEPOSIT', 'Cheque deposit'), ('CASH DEPOSIT', 'Cash deposit'), ('CARD TRANSFER', 'Card transfer')], max_length=50)),
                ('deposit_type', models.CharField(choices=[('LOAN_REPAYMENT', 'Loan repayment'), ('SHARES', 'Shares')], max_length=20)),
                ('transaction_desc', models.CharField(max_length=200)),
                ('time_deposited', models.DateTimeField()),
                ('other_info', models.TextField(blank=True, max_length=10000)),
                ('time_created', models.DateField(auto_now=True)),
                ('circle_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember')),
            ],
            options={
                'db_table': 'Deposit',
            },
        ),
    ]
