# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circle', '0001_initial'),
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntraCircleShareTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.FloatField(default=0.0)),
                ('time_of_transaction', models.DateTimeField(auto_now=True)),
                ('extra_info', models.TextField(max_length=10000)),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='circle.CircleMember')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='circle.CircleMember')),
            ],
            options={
                'db_table': 'IntraCircleShareTransfer',
            },
        ),
        migrations.CreateModel(
            name='LockedShares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.FloatField(default=0.0)),
                ('transaction_description', models.TextField(max_length=1000)),
                ('time_of_transaction', models.DateTimeField(auto_now=True)),
                ('extra_info', models.TextField(max_length=10000)),
                ('circle_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember')),
            ],
            options={
                'db_table': 'LockedShares',
            },
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.FloatField(default=0.0)),
                ('time_acquired', models.DateTimeField(null=True)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('circle_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember')),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deposit.Deposit')),
                ('intra_share_transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shares.IntraCircleShareTransfer')),
            ],
            options={
                'db_table': 'Shares',
            },
        ),
        migrations.CreateModel(
            name='UnlockedShares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.FloatField(default=0.0)),
                ('transaction_description', models.TextField(max_length=1000)),
                ('time_of_transaction', models.DateTimeField(auto_now=True)),
                ('extra_info', models.TextField(max_length=10000)),
                ('circle_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember')),
            ],
            options={
                'db_table': 'UnlockedShares',
            },
        ),
    ]
