# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedGuarantorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AllowedGuarantorRequest',
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_type', models.CharField(choices=[(b'PRIVATE', b'Private circle'), (b'OPEN', b'Open circle')], max_length=10)),
                ('circle_acc_number', models.CharField(max_length=100, unique=True)),
                ('time_initiated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annual_interest_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'Circle',
            },
        ),
        migrations.CreateModel(
            name='CircleDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateField()),
                ('duration_of_tenure', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CircleDirector',
            },
        ),
        migrations.CreateModel(
            name='CircleInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('time_invited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CircleInvitation',
            },
        ),
        migrations.CreateModel(
            name='CircleMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_acc_number', models.CharField(max_length=10)),
                ('allow_public_guarantees_request', models.BooleanField(default=True)),
                ('time_joined', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.Circle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'CircleMember',
            },
        ),
        migrations.AddField(
            model_name='circleinvitation',
            name='circle_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember'),
        ),
        migrations.AddField(
            model_name='circleinvitation',
            name='invited_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='circledirector',
            name='circle_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember'),
        ),
        migrations.AddField(
            model_name='allowedguarantorrequest',
            name='allows_request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allows_request_from', to='circle.CircleMember'),
        ),
        migrations.AddField(
            model_name='allowedguarantorrequest',
            name='circle_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_member', to='circle.CircleMember'),
        ),
    ]
