# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circle', '0001_initial'),
        ('deposit', '0001_initial'),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuarantorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.FloatField(default=0.0)),
                ('time_requested', models.DateTimeField(auto_now=True)),
                ('has_accepted', models.NullBooleanField(choices=[(None, 'Pending approval'), (True, 'Accepted to guarantee applicant'), (False, 'Denied to guarantee applicant')], default=None)),
                ('time_accepted', models.DateTimeField(null=True)),
                ('circle_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember')),
            ],
            options={
                'db_table': 'GuarantorRequest',
            },
        ),
        migrations.CreateModel(
            name='LoanAmortizationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateField()),
                ('min_amount_payable', models.FloatField()),
            ],
            options={
                'db_table': 'LoanAmortizationSchedule',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_code', models.CharField(max_length=10, unique=True)),
                ('amount', models.FloatField(default=0.0)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('repayment_cycle', models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], max_length=5)),
                ('num_of_repayment_cycles', models.IntegerField(default=1)),
                ('require_guarantors', models.BooleanField(default=False)),
                ('time_of_application', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('time_approved', models.DateTimeField(null=True)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('time_disbursed', models.DateTimeField(null=True)),
                ('disbursement_channel', models.CharField(choices=[('MPESA', 'M-pesa'), ('BANK_ACCOUNT', 'Bank Account')], max_length=20)),
                ('other_info', models.TextField(blank=True, max_length=10000)),
                ('is_fully_repaid', models.BooleanField(default=False)),
                ('time_of_last_payment', models.DateTimeField(null=True)),
                ('circle_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember')),
            ],
            options={
                'db_table': 'LoanApplication',
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_requested', models.DateTimeField(auto_now=True)),
                ('circle_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleMember')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanApplication')),
                ('locked_shares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.LockedShares')),
            ],
            options={
                'db_table': 'LoanGuarantor',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('time_of_repayment', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.Deposit')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanApplication')),
            ],
            options={
                'db_table': 'LoanRepayment',
            },
        ),
        migrations.AddField(
            model_name='loanamortizationschedule',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanApplication'),
        ),
        migrations.AddField(
            model_name='guarantorrequest',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanApplication'),
        ),
    ]
