# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('relationship', models.CharField(choices=[(b'CHILD', b'Child'), (b'SPOUSE', b'Spouse'), (b'PARENT', b'Parent'), (b'OTHER', b'Other')], max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('passport_image', models.FileField(blank=True, null=True, storage=b'BENEFICIARY_PASSPORT_IMAGE', upload_to=b'')),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Beneficiary',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(null=True)),
                ('passport_image', models.FileField(blank=True, null=True, storage=b'MEMBER_PASSPORT_IMAGE', upload_to=b'')),
                ('registered_device', models.TextField(blank=True, max_length=1000)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('time_registered', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='MemberActiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_info', models.TextField(blank=True, max_length=1000)),
                ('session_start_time', models.DateTimeField(auto_now=True)),
                ('session_end_time', models.DateTimeField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'MemberActiveSession',
            },
        ),
        migrations.CreateModel(
            name='MemberBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'MemberBankAccount',
            },
        ),
        migrations.CreateModel(
            name='MemberBankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('expires_on', models.CharField(max_length=5)),
                ('card_verification_value', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'MemberBankCard',
            },
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('registered_device', models.TextField(blank=True, max_length=1000)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('has_agreed_to_terms', models.BooleanField(default=False)),
                ('universal_transaction_pin', models.CharField(blank=True, max_length=1000)),
                ('national_id_confirmed', models.BooleanField(default=False)),
                ('phone_number_confirmed', models.BooleanField(default=False)),
                ('email_address_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PendingRegistration',
            },
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
