# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170720_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='passport_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'MEDIA/MEMBER_PASSPORT_PICS'),
        ),
    ]
