# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170720_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passport_image',
            field=models.FileField(blank=True, null=True, upload_to=b'MEDIA/MEMBER_PASSPORT_PICS'),
        ),
    ]
