# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_of_circles', models.IntegerField()),
            ],
            options={
                'db_table': 'AppSetting',
            },
        ),
        migrations.CreateModel(
            name='CircleTermsOfUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(max_length=1500, unique=True)),
                ('time_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CircleTermsOfUse',
            },
        ),
    ]
